workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
    scripts:
      - name: Ensure Android platform exists
        script: |
          if [ ! -d "android" ]; then
            flutter create . --org com.framerate.app --platforms=android
          else
            flutter create . --org com.framerate.app --platforms=android --overwrite
          fi
      - name: Install dependencies
        script: |
          flutter packages get
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
