workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
    scripts:
      - name: Generate Native Android Folder
        script: |
          flutter create . --org com.framerate.app --platforms=android
      - name: Install dependencies
        script: |
          flutter packages get
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
