name: framerate
description: "Framerate - The ultimate media and franchise tracking app with custom themes, micro-animations, and dynamic app icon themes."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    
